import type { MetadataRoute } from "next";
import { DOCS_URL } from "@/lib/config";

/**
 * robots.txt for the docs subdomain.
 *
 * There was no robots.txt in this repo — the one served at
 * docs.vnytros.dev/robots.txt is generated by Cloudflare's managed
 * robots.txt feature. It allows search engines, so indexing was never
 * blocked, but it is not version-controlled and, critically, it carries
 * no `Sitemap:` line.
 *
 * This puts the file under source control and points crawlers at the
 * sitemap. NOTE: if Cloudflare's managed robots.txt is still enabled it
 * may continue to shadow this route — check the live URL after deploy,
 * and submit the sitemap directly in Search Console either way rather
 * than relying on discovery.
 */
export const dynamic = "force-static";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },
    sitemap: `${DOCS_URL}/sitemap.xml`,
    host: DOCS_URL,
  };
}
